name: 'Setup App Token and Google Auth'
description: 'Create GitHub App token and authenticate with Google Cloud'
inputs:
  app-id:
    description: 'GitHub App ID'
    required: false
    default: '1328202'
  private-key:
    description: 'GitHub App private key'
    required: true
  workload-identity-provider:
    description: 'Workload identity provider for Google Cloud'
    required: false
    default: 'projects/925362051349/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider'
  service-account:
    description: 'Service account for Google Cloud'
    required: false
    default: 'github-actions@ubie-gl-claude-actions-prd.iam.gserviceaccount.com'

outputs:
  token:
    description: 'Generated GitHub App token'
    value: ${{ steps.app-token.outputs.token }}
  project-id:
    description: 'Google Cloud project ID'
    value: ${{ steps.auth.outputs.project_id }}

runs:
  using: 'composite'
  steps:
    - name: Create GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
        owner: ubie-inc

    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}